set nocompatible
set shiftwidth=4
set tabstop=4
set scrolloff=15
set ignorecase
set omnifunc=syntaxcomplete#Complete
set number
set wrap
set linebreak
set encoding=utf-8
set showcmd
set showmatch
set wildmenu
set smarttab
set hlsearch
set incsearch
set cc=
set clipboard=unnamedplus
set wildmode=longest:full,full
set title
set completeopt-=preview
set background=dark
set statusline+=%F
set laststatus=2
